let storage = {
    onama: [
        {
            naziv: "VARIONICA",
            label: "Mjesto gdje se pibo kuha je srce nase pivovare",
            opis: "Varionicu (brewhouse) dizajnirali smo sami kako bi bila maksimalno prilagođena našim potrebama i željama. U jednom kuhanju možemo proizvesti 6.000 litara sladovine koja će kasnije postati pivo. Automatizirana varionica je računalno vođena što nam omogućuje bolju kontrolu procesa, veću standardizaciju te paralelno kuhanje 6-7 uvaraka dnevno. Bakreni detalj na modernom dizajnu podsjetnik je na našu tradiciju. Proces kuhanja piva u varionici traje 6 – 8 sati. Sastoji se od ukomljavanja (miješanje slada s vrućom vodom kako bi se iz slada oslobodio šećer za fermentaciju), cijeđenja (odvajanje sladovine od tropa, koji prodajemo lokalnim farmerima kao prvoklasnu stočnu hranu), kuhanja (steriliziranje sladovine kuhanjem i dodavanje hmelja) te whirlpoola (odvajanje preostalih čestica iz sladovine te eventualno dodatno dodavanje hmelja). Nakon toga, sladovina se hladi i prebacuje u fermentore.",
            img: "https://m-blog.vecernji.hr/media/content_blog_images/8bedaf1d118ab3aa02249f9c59edec62.jpg",
        },
        {
            naziv: "PODRUM",
            label: "U podrumu za fermentaciju i odležavanje događa se magija: sladovina postaje pivo",
            opis: "Nakon kuhanja pivo se hladi i u njega se dodaje kvasac koji će u idućim danima, hraneći se šećerom, sladovinu pretvoriti u pivo odnosno u alkohol i CO2. Ovisno o vrsti piva koju kuhamo, koriste se lager ili ale kvasac. Nakon otprilike tjedan dana fermentacije, kvasac je završio s poslom i napravio pivo koje će odležati još nekoliko tjedana kako bi se formirali okusi i arome. U neka se piva dodaje hmelj procesom suhog hmeljenja, direktnim ubacivanjem hmelja u tank za odležavanje, kako bi se dodatno postigle neodoljive arome. Naš podrum se sastoji od tankova od 3.000, 6.000, 12.000 te 24.000 litara u kojima pivo fermentira i odležava.",
            img: "https://www.telegram.hr/wp-content/uploads/2019/05/medvedgrad-2-1.jpg",
        },
        {
            naziv: "PUNJENJE",
            label: "Kvalitetan proces punjenja piva ključan je za vrhunski proizvod",
            opis: "Punilica za boce omogućuje nam značajno ubrzanje i poboljšanje kvalitete punjenja, a zbog minimalne količine preostalog kisika u bocama vijek trajanja piva je povećan. Točeno pivo strojno se puni u kegove od 10, 20, 30 i 50 litara. Svoja piva ne filtriramo, a kako bismo dodatno osigurali konzistentnost i kvalitetu koristimo centrifugalni separator s kojim postižemo bistrinu.",
            img: "https://www.vecernji.hr/media/img/c1/a2/4d6fb46502e608e6691d.jpeg",
        },
        {
            naziv: "KONTROLA",
            label: "Labaratorij kontrolira svaki korak proizvodnje",
            opis: "Laboratorij je opremljen vrhunskom opremom za kontrolu kvalitete piva. Svakodnevno se rade fizikalno-kemijske i mikrobiološke analize kako bi se osigurala kvaliteta gotovog proizvoda. Pivo ujednačene kvalitete rezultat je stalnog nadzora proizvodnog procesa, u kojem pratimo boju, alkohol, CO2, ph, IBU i mikrobiološku stabilnost piva.",
            img: "image.png",
        },
        {
            naziv: "HLADNI LANAC",
            label: "Hladno skladištenje i hladni transport",
            opis: "Kada je pivo napunjeno, proces brige i upravljanja samim pivom nije završen. Prije same konzumacije potrebno je osigurati da se pivo skladišti i prevozi u kvalitetnim uvjetima. Naše prirodno pivo bez konzervansa uvijek mora biti na hladnom i, po mogućnosti, mračnom mjestu.",
            img: "https://prehrambeno-tehnoloska-skola.hr/wp-content/uploads/2022/05/279846556_1101245633768835_8296141467240793424_n.jpg",
        }
    ],
    piva: [
        {

            id: 10001,
            tip: "Stalna Piva",
            naziv: "Zlatni Medvjed",
            vrstaPiva: "Pilsner",
            postotakAlkohola: 4.4,
            gorcina: 22,
            uravnoteziteljSSK: "1 - 12",
            img: "https://d17zv3ray5yxvp.cloudfront.net/variants/XPiP4zHDdrZCFpCv5iqfhVC...",
            opis: "Prirodni craft lager kuhan od najboljeg pilsner slada te hmeljeva Aurora, Golding i Saaz.",

        },
        {
            id: 10002,
            tip: "Stalna Piva",
            naziv: "Crna Kraljica",
            vrstaPiva: "Crni lager",
            postotakAlkohola: 4.8,
            gorcina: 20,
            uravnoteziteljSSK: "1 - 12",
            img: "https://d17zv3ray5yxvp.cloudfront.net/variants/GTpTUrGtXus1WbTKLsqPzJN...",
            opis: "Crni lager izraženog okusa i arome prženog slada i ječma no izuzetnog balansa i pitkosti.",

        },
        {
            id: 10003,
            tip: "Stalna Piva",
            naziv: "Grička Vještica",
            vrstaPiva: "Doppelbock",
            postotakAlkohola: 7.5,
            gorcina: 21,
            uravnoteziteljSSK: "1 - 12",
            img: "https://www.cro-craft.com/wp-content/uploads/medvedgrad-grickavjestica...",
            opis: "Ukusno, kremasto i pitko pivo ugodne slatkoće te bogatog sladnog karaktera. ",
        },
        {
            id: 10004,
            tip: "Stalna Piva",
            naziv: "Baltazar",
            vrstaPiva: "Hoppy lager",
            postotakAlkohola: 5.0,
            gorcina: 45,
            uravnoteziteljSSK: "1 - 12",
            img: "",
            opis: "Osvježavajuć kao lager, zahmeljen kao ale. Dominira prekrasna voćna aroma te ugodna gorčina.",
        },
        {
            id: 10005,
            tip: "Stalna Piva",
            naziv: "Fakin Ipa",
            vrstaPiva: "India Pale Ale",
            postotakAlkohola: 6.5,
            gorcina: 55,
            uravnoteziteljSSK: "1 - 12",
            img: "",
            opis: "Izraziti hmeljni karakter i gorčina u okusu koji se fakinski neustrašivo spajaju s bogatom voćnom aromom.",
        },
        {
            id: 10006,
            tip: "Stalna Piva",
            naziv: "Dva Klasa",
            vrstaPiva: "Weizenbier",
            postotakAlkohola: 4.6,
            gorcina: 20,
            uravnoteziteljSSK: "1 - 12",
            img: "",
            opis: "Mutno pivo specifičnog okusa i arome koji potječu od pšeničnog slada i kvasca za pšenično pivo.",
        },
        {
            id: 10007,
            tip: "Sezonska piva",
            naziv: "Agram Stout",
            vrstaPiva: "Stout",
            postotakAlkohola: 5.5,
            gorcina: 30,
            uravnoteziteljSSK: "1 - 12",
            img: "",
            opis: "Klasični stout u kojem dominiraju okusi kave te nešto manje i čokolade, suh završetak. Izlazi u veljači.",
        },
        {
            id: 10008,
            tip: "Sezonska piva",
            naziv: "Novi Val",
            vrstaPiva: "India Pale Ale",
            postotakAlkohola: 5.7,
            gorcina: 55,
            uravnoteziteljSSK: "1 - 12",
            img: "",
            opis: "Drugačijeg okusa, vrhunskog balansa i prekrasne arome tri egzotična hmelja novog svijeta. IPA napravljena u čast zagrebačkom Novom valu osamdesetih godina. Izlazi krajem travnja.",
        },
        {
            id: 10009,
            tip: "Sezonska Piva",
            naziv: "Ljeto u Zagrebu",
            vrstaPiva: "Witbier",
            postotakAlkohola: 4.8,
            gorcina: 22,
            uravnoteziteljSSK: 1 - 12,
            img: "",
            opis: "Belgijsko pšenično pivo pripremljeno od ječmenog i pšeničnog slada te zobi s dodatkom kore gorke naranče i korijandera. Izlazi krajem lipnja.",
        },
        {
            id: 10010,
            tip: "Sezonska Piva",
            naziv: "Vragec",
            vrstaPiva: "Session IPA",
            postotakAlkohola: 4.8,
            gorcina: 45,
            uravnoteziteljSSK: "1 - 12",
            img: "",
            opis: "Vragolasta IPA s manje alkohola, pitka, balansirana s puno voćnih aroma koje dolaze od četiri vrste hmelja. Izlazi krajem kolovoza.",
        },
        {
            id: 10011,
            tip: "Sezonska Piva",
            naziv: "Crni Jack",
            vrstaPiva: "Crna IPA",
            postotakAlkohola: 6.6,
            gorcina: 55,
            uravnoteziteljSSK: "1 - 12",
            img: "",
            opis: "Kavasto - čokoladne note ove IPA-e spojene su s eksplozijom hmeljnog karaktera. Izlazi početkom listopada.",
        },
        {
            id: 10012,
            tip: "Sezonska Piva",
            naziv: "Božićno pivo",
            vrstaPiva: "Jaki crni lager",
            postotakAlkohola: 6.9,
            gorcina: 23,
            uravnoteziteljSSK: "1 - 12",
            img: "",
            opis: "Crno jako pivo, vrlo bogatog okusa, mirisa i teksture koje proizlazi iz bogate mješavine slada pripremljene tradicionalno za božićne blagdane. Izlazi početkom studenog.",
        },
        {
            id: 10013,
            tip: "Fantom",
            naziv: "Fantom 27",
            vrstaPiva: "IPA New England/Hazy",
            postotakAlkohola: 6.2,
            gorcina: 40,
            uravnoteziteljSSK: "1 - 12",
            img: "",
            opis: " New England IPA vrlo bogatog okusa, mirisa i teksture, prepun arome, zahmeljen ali vrlo pitak ",
        },
        {
            id: 10013,
            tip: "Fantom",
            naziv: "Fantom 25",
            vrstaPiva: "India Pale Lager",
            postotakAlkohola: 5.8,
            gorcina: 42,
            uravnoteziteljSSK: "1 - 12",
            img: "",
            opis: "Plava kapa znači samo jedno – da smo skuhali IPL u kojem lager kvasac svojom čistoćom prekrasno ističe karakteristike hmeljeva, a ovoga puta to su: Citra, Mosaic incognito, Mosaic spectrum i HBC 586. Obilježavaju ga citrusne i tropske arome te idealni balans gorčine i tijela. Vrlo je pitak, stvoren za uživanje!",
        },
        {
            id: 10014,
            tip: "Fantom",
            naziv: "Fantom 24",
            vrstaPiva: "IPA American",
            postotakAlkohola: 6.4,
            gorcina: 42,
            uravnoteziteljSSK: "1 - 12",
            img: "",
            opis: "Klasična američka IPA, s hmeljevima koji podsjećaju na citrusno i tropsko voće, pomiješano s aromama cvijeća i borovine. Suši završetak s pojačanom sladnom notom i niža gorčina – zaokruženi su u savršeni balans.",
        },
        {
            id: 10015,
            tip: "Fantom",
            naziv: "Fantom 23",
            vrstaPiva: "India Pale Lager",
            postotakAlkohola: 6.7,
            gorcina: 30,
            uravnoteziteljSSK: "1 - 12",
            img: "",
            opis: "Ukusni, sočni lager prepun arome, zahmeljen ali vrlo pitak",
        },

    ],

    /* 
    {
                id: ,
                tip:,
                naziv: "",
                vrstaPiva: "",
                postotakAlkohola: ,
                gorcina: ,
                uravnoteziteljSSK: ,
                opis: ,
            },
    */
    pivovare: [

        {
            nazivPivovare: "Ilica",
            adresa: "Ilica 49",
            telefon: "01/4846-922",
            fax: "01 / 3646 - 559",
            radnoVrijeme: "10 - 24",
            opis: "Smještena na manje od 100 metara križanja Ilice i Frankopanske, ova pivnica svojom velikom zelenom terasom predstavlja pravu pivničku oazu koja nikoga neće ostaviti ravnodušnim. Osim toga, tu je i mala privatna terasa idealna za obiteljska druženja i sl. U Ilici vas čekaju naši poznati pivnički specijaliteti i vrhunsko Medvedgrad pivo, karakterističan hrastov namještaj te već spomenuta zelena terasa koji će vam pružiti poseban doživljaj!",
        },
        {
            nazivPivovare: "Fakin craft bar",
            adresa: "Vukovarska 68",
            telefon: "01 / 6293 - 377",
            fax: "01 / 62933 - 377",
            radnoVrijeme: "9 - 22",
            opis: "Fakin Craft Bar nastao je s namjerom da dosadašnji tip pivnica nadogradimo novim idejama i pokušamo prilagoditi današnjem vremenu. Šank s 24 pipe za točenje posebna je konstrukcija s četiri odvojene rashladne zone kojima želimo gostu pružiti užitak konzumacije piva poslužene na preporučenim temperaturama. U jednom dijelu prostora instalirana je i mikro pivovara s varionicom od 50 litara. Svatko tko želi može doći i skuhati svoje pivo na našoj opremi. Potrebno nas je kontaktirati i dogovoriti termin kuhanja.",


        },
        {
            nazivPivovare: "Mali medo",
            adresa: "Tkalčićeva 36",
            telefon: "01 / 4929 - 613",
            fax: "01 / 4929 - 614",
            radnoVrijeme: "10 - 22",
            opis: "Pivnica smještena u Tkalčićevoj ulici, nudi vam priliku okusiti djelić pivničkog šarma u srcu Zagreba. Mali Medo  davno je prestao biti mali, sada se vanjska terasa proteže velikim dijelom Tkalčićeve ulice gdje je moguće smjestiti preko 400 gostiju. Uz samu pivnicu otvorena je i suvenirnica u kojoj možete kupiti pivo u boci i pivničke suvenire s potpisom Medvedgrada; majice, krigle i sl. Zatim pizzeria, linija brze hrane s odličnim rebarcima i krilcima, slasni Mason burgeri, te Burza piva gdje nikada nećete doživjeti “crni petak”!"

        },
        {
            nazivPivovare: "Samoborska",
            adresa: "Samoborksa cesta 217",
            telefon: "098 399 319",
            fax: "01 / 3646-549",
            radnoVrijeme: "10 - 22",
            opis: "Na Samoborskoj cesti ne nalazi se samo pivnica Medvedgrad već i pogon same pivovare. Dok ispijate omiljeno pivo, kroz staklene površine imate priliku gledati kako se ono priprema. Osim naših poznatih pivničkih specijaliteta u Samoborskoj vas čeka i roštilj na drveni ugljen. U prekrasnoj dvorani na prvom katu pivnice moguće je organizirati privatne proslave za 80 ljudi, a parking je osiguran za sve naše goste. Također, možete kupiti naše pivo u bocama po vrlo povoljnim, outlet cijenama.",
        }
    ],



    rezervacije: [
        {
            broj_rezervacije: 101,
            ime: "Stela",
            prezime: "Gal",
            telefon: "0919805009",
            username: "stela@gmail.com",
            datum: 7645446873487,
            tipRezervacije: "rucak",
            vrijeme: "13:00",
            brojOsoba: 2,
            izborPivnice: "Ilica",
            napomena: "Napomena za rezervaciju"

        },

        {
            broj_rezervacije: 102,
            ime: "Petar",
            prezime: "Simic",
            telefon: "0919805119",
            username: "petar@gmail.com",
            datum: 2245489873487,
            tipRezervacije: "vecera",
            vrijeme: "19:00",
            brojOsoba: 3,
            izborPivnice: "Mali medo",
            napomena: "Napomena za rezervaciju"
        },

        {
            broj_rezervacije: 103,
            ime: "Ante",
            prezime: "Pekić",
            telefon: "0919888896",
            username: "ante@gmail.com",
            datum: 7645446873487,
            tipRezervacije: "rucak",
            vrijeme: "12:00",
            brojOsoba: 4,
            izborPivnice: "Samoborska",
            napomena: "Napomena za rezervaciju"
        },
    ]
}


export default storage;